import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/session-provider";
import { authOptions } from "@/utils/auth-options";
import HeaderContainer from "@/components/HeaderContainer/HeaderContainer";
import { ChildrenFCProps } from "@repo/common/models";
import { BrandTitle } from "@repo/ui/brand-title";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: ChildrenFCProps): Promise<JSX.Element> {
  const session = await getServerSession(authOptions);
  return (
    <html lang="es">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <HeaderContainer>
            <BrandTitle />
          </HeaderContainer>
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
