import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import ComposeProviders from "src/providers/compose-providers";
import { authOptions } from "src/utils/auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  const session = await getServerSession(authOptions);
  return (
    <html lang="es">
      <head>
        <link href="/favicon.png" rel="icon" />
      </head>
      <ComposeProviders session={session}>
        <body className={inter.className}>{children}</body>
      </ComposeProviders>
    </html>
  );
}
